### ISSUE TITLE
Move completions to oh-my-zsh completions

### ISSUE THREAD

**Issue by sugarraysam** [sugarraysam/archsugar#3]
# or if you use oh-my-zsh (needs zsh-completions plugin)
        % mkdir $ZSH/completions/
        % kind completion zsh > $ZSH/completions/_kind

**Comment by sugarraysam** [comment]
```bash
mkdir ~/.oh-my-zsh/completions
gopass completion zsh > ~/.oh-my-zsh/completions/_gopass
```

Add to base scenario, a `completions` object:

```yaml
- { cmd: "gopass completion zsh", dest: "_gopass" }
- { cmd: "kind completion zsh", dest: "_kind" }

and scenario does:
- name: Setup completions
  shell: 
    cmd: "{{ item.cmd }} > {{ user_home }}/.oh-my-zsh/{{ item.dest }}"
  loop: "{{ completions }}"
```
